float:
  angular:
  - base_args: ['@metric', '@dimension']
    constructor: OpenSearchKNN
    disabled: false
    docker_tag: ann-benchmarks-opensearchknn
    module: ann_benchmarks.algorithms.opensearchknn
    name: opensearchknn
    run_groups:
      M-16-efc-100:
        arg_groups: [{M: 16, efConstruction: 100}]
        args: {}
        query_args: [[ 100, 128, 256, 512]]
      M-16-efc-128:
        arg_groups: [ { M: 16, efConstruction: 128 } ]
        args: { }
        query_args: [ [ 100, 128, 256, 512 ] ]
      M-16-efc-256:
        arg_groups: [ { M: 16, efConstruction: 256 } ]
        args: { }
        query_args: [ [ 100, 128, 256, 512 ] ]
      M-16-efc-512:
        arg_groups: [ { M: 16, efConstruction: 512 } ]
        args: { }
        query_args: [ [ 100, 128, 256, 512 ] ]
      M-12-efc-100:
        arg_groups: [{M: 12, efConstruction: 100}]
        args: {}
        query_args: [[ 100, 128, 256, 512]]
      M-12-efc-128:
        arg_groups: [ { M: 12, efConstruction: 128 } ]
        args: { }
        query_args: [ [ 100, 128, 256, 512 ] ]
      M-12-efc-256:
        arg_groups: [ { M: 12, efConstruction: 256 } ]
        args: { }
        query_args: [ [ 100, 128, 256, 512 ] ]
      M-12-efc-512:
        arg_groups: [ { M: 12, efConstruction: 512 } ]
        args: { }
        query_args: [ [ 100, 128, 256, 512 ] ]
  euclidean:
  - base_args: ['@metric', '@dimension']
    constructor: OpenSearchKNN
    disabled: false
    docker_tag: ann-benchmarks-opensearchknn
    module: ann_benchmarks.algorithms.opensearchknn
    name: opensearchknn
    run_groups:
      M-16-efc-100:
        arg_groups: [{M: 16, efConstruction: 100}]
        args: {}
        query_args: [[ 100, 128, 256, 512]]
      M-16-efc-128:
        arg_groups: [ { M: 16, efConstruction: 128 } ]
        args: { }
        query_args: [ [ 100, 128, 256, 512 ] ]
      M-16-efc-256:
        arg_groups: [ { M: 16, efConstruction: 256 } ]
        args: { }
        query_args: [ [ 100, 128, 256, 512 ] ]
      M-16-efc-512:
        arg_groups: [ { M: 16, efConstruction: 512 } ]
        args: { }
        query_args: [ [ 100, 128, 256, 512 ] ]
      M-12-efc-100:
        arg_groups: [{M: 12, efConstruction: 100}]
        args: {}
        query_args: [[ 100, 128, 256, 512]]
      M-12-efc-128:
        arg_groups: [ { M: 12, efConstruction: 128 } ]
        args: { }
        query_args: [ [ 100, 128, 256, 512 ] ]
      M-12-efc-256:
        arg_groups: [ { M: 12, efConstruction: 256 } ]
        args: { }
        query_args: [ [ 100, 128, 256, 512 ] ]
      M-12-efc-512:
        arg_groups: [ { M: 12, efConstruction: 512 } ]
        args: { }
        query_args: [ [ 100, 128, 256, 512 ] ]

