float:
  angular:
  - base_args: ['@metric', '@dimension']
    constructor: OpenSearchKNN
    disabled: false
    docker_tag: ann-benchmarks-opensearchknn
    module: ann_benchmarks.algorithms.opensearchknn
    name: opensearchknn
    run_groups:
      M-16:
        arg_groups: [{M: 16, efConstruction: 256}]
        args: {}
        query_args: [[128, 256, 512]]
  euclidean:
  - base_args: ['@metric', '@dimension']
    constructor: OpenSearchKNN
    disabled: false
    docker_tag: ann-benchmarks-opensearchknn
    module: ann_benchmarks.algorithms.opensearchknn
    name: opensearchknn
    run_groups:
      M-16:
        arg_groups: [{M: 16, efConstruction: 256}]
        args: {}
        query_args: [[128, 256, 512]]
